useTabs: true
tabWidth: 2

printWidth: 100

singleQuote: false
trailingComma: es5
semi: true
jsxBracketSameLine: false

parser: babel-ts

overrides:
  - files: "*.css"
    options:
      parser: css

  - files: "*.{yaml,yml}"
    options:
      parser: yaml

  - files: "*.md"
    options:
      parser: markdown
